# Project/run identifiers
project: classification_pd
run_name: local-run

# Model and training hyperparameters
n_folds:             5
n_epochs:            250
ll_out_units: 2

param_grid:
  lr:
    - 0.001
    - 0.005
    - 0.01
  weight_decay:
    - 1e-4
    - 1e-3
  cl1_hidden_units:
    - 16
    - 32
  cl2_hidden_units:
    - 8
    - 16
  dropout:
    - 0.3
    - 0.5
  lrscheduler_factor:
    - 0.1
    - 0.5