# Project/run identifiers
project: gcn
run_name: local-run

# Model and training hyperparameters
n_folds:             5
n_epochs:            250
lr:                   0.005
weight_decay:         0.0001
cl1_hidden_units:     32
cl2_hidden_units:     8
ll_out_units:         1
dropout:              0.5
lrscheduler_factor:   0.5
model_name:          "GCNN"
